# User Roles
ROLE_SUPERADMIN = "SUPERADMIN"
ROLE_ADMIN = "ADMIN"
ROLE_DOCTOR = "DOCTOR"
ROLE_RECEPTIONIST = "RECEPTIONIST"

ROLE_CHOICES = [
    (ROLE_SUPERADMIN, "Super Admin"),
    (ROLE_ADMIN, "Admin"),
    (ROLE_DOCTOR, "Doctor"),
    (ROLE_RECEPTIONIST, "Receptionist"),
]

# Appointment Status
APPOINTMENT_PENDING = "PENDING"
APPOINTMENT_CONFIRMED = "CONFIRMED"
APPOINTMENT_CANCELLED = "CANCELLED"
APPOINTMENT_COMPLETED = "COMPLETED"

APPOINTMENT_STATUS_CHOICES = [
    (APPOINTMENT_PENDING, "Pending"),
    (APPOINTMENT_CONFIRMED, "Confirmed"),
    (APPOINTMENT_CANCELLED, "Cancelled"),
    (APPOINTMENT_COMPLETED, "Completed"),
]